# -------------------------------------------------
# Site metadata
# -------------------------------------------------
title: Aero2
description: A design-first Jekyll theme inspired by print layout and early web UI.
tagline: Confident structure. Clear hierarchy.

url: https://example.com
baseurl: ""

lang: en
timezone: America/Denver

# -------------------------------------------------
# Theme
# -------------------------------------------------
theme: jekyll-theme-aero2

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# -------------------------------------------------
# Defaults
# -------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: retro

  - scope:
      path: ""
      type: posts
    values:
      layout: post

# -------------------------------------------------
# Basics
# -------------------------------------------------
markdown: kramdown
highlighter: rouge
permalink: pretty

# -------------------------------------------------
# Kramdown + Rouge
# -------------------------------------------------
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
